In [1]:
import	pandas	as	pd
from	sqlalchemy	import	create_engine
#	psql
import	psycopg2

In [3]:
df	=	pd.read_csv('Walmart_data.csv',	encoding_errors='ignore')
df.shape

(10051, 11)

In [4]:
df.head()
df.describe()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [5]:
#	all	duplicates
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()
df.shape

(10000, 11)

In [6]:
df.isnull().sum()
#	dropping	all	rows	with	missing	records
df.dropna(inplace=True)
#	verify
df.isnull().sum()
df.shape

(9969, 11)

In [7]:
df.dtypes
#	unit_price	is	text	with	a	$	sign	->	convert	to	float
df['unit_price']	=	df['unit_price'].str.replace('$',	
'').astype(float)

In [8]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [10]:
df.columns
df['total']	=	df['unit_price']	*	df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [11]:
df.columns
df.columns	=	df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='str')

In [19]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:9554561256p@localhost:5432/walmart"
)

df.to_sql(
    "walmart",
    con=engine,
    if_exists="replace",
    index=False
)

969